name: charlescd-prod-update

on:
  release:
    types:
      - released
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_prerelease
    steps:
    - uses: actions/checkout@v2

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)

    - name: Update charts
      run: |
        mv ./install/helm-chart/Chart.yaml ./install/helm-chart/Chart.old.yaml &&
        cat ./install/helm-chart/Chart.old.yaml | grep -v appVersion > ./install/helm-chart/Chart.yaml &&
        echo -e "\r\nappVersion: ${{ steps.get_version.outputs.VERSION }}\r\n" >> ./install/helm-chart/Chart.yaml &&
        cat ./install/helm-chart/Chart.yaml
    - name: Deploy
      uses: WyriHaximus/github-action-helm3@v1
      with:
        exec: helm upgrade Charles-CD ./install/helm-chart/ --install --wait --atomic --namespace=charles --values=./install/helm-chart/values.yaml
        kubeconfig: '${{ secrets.KUBECONFIG }}'
